### ISSUE TITLE
Add P.2 as VoI to curated mutations list

### ISSUE THREAD

**Issue by gkarthik** [andersen-lab/hCoV19-sitrep#3]

**Comment by flaneuse** [comment]
Just because of E484K?  Has anyone else classified it as a VOI?

Looking at the temporal traces, it doesn't seem to me like it's increasing much in the world, US, Brazil, Australia, Argentina...

**Comment by gkarthik** [comment]
I figured worth a discussion. P.2 as VoI seems subjective at this point.

**Comment by flaneuse** [comment]
My vote is no now.  Would support it moving to a VOI if CDC, WHO, PHE indicate it is one or growth rates in a particular place(s) show escalation.
